### PR TITLE
Add ExposePorts Option

### PR DESCRIPTION
**Pull request by mbobrovskyi**
Add ExposePorts Option that allow to open a custom port on create container.

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
@dhui Can you merge this changes ?

**Comment by mbobrovskyi** [comment]
@dhui Could you please check this pull request? Or close if not valid?

**Comment by sam-kleiner** [comment]
Bumping this since its needed to fix https://github.com/golang-migrate/migrate/pull/917

It looks like my issue there was the dockerfile for surrealdb does not expose ports, while most other images used in migrate tests do. This allows me to override that when creating the container.

**Comment by mbobrovskyi** [comment]
@dhui Any updates here?

**Comment by sam-kleiner** [comment]
@dhui if you have time time would you please review this? I have confirmed it fixes the issues I was having in migrate.

**Comment by mbobrovskyi** [comment]
@dhui Please take a look :pray:. I also fixed `TestRunWithExposesPorts`. This changes very important for us, because we can't move on with https://github.com/golang-migrate/migrate/pull/881 and https://github.com/golang-migrate/migrate/pull/917.

**Review by dhui — APPROVED** [review]
@mbobrovskyi @sam-kleiner thanks for your patience!

**Comment by sam-kleiner** [comment]
> @mbobrovskyi @sam-kleiner thanks for your patience!

No worries I know we are all busy. Thanks for merging! Migrate is killer btw, love using it.

**Pull request merged**
