### PR TITLE
remove image to save space and cleanup when container stopped after the execution

### PR DESCRIPTION
**Pull request by mkorolyov**
when executing a lot of tests with lots of docker images on CI we can face the problem of insufficient space. Also, it is a good practice to cleanup data/space/etc after the tests are done.

### CODE REVIEW

**Comment by guy9** [comment]
Interested in this as well

**Comment by annastuchlik** [comment]
+1

**Comment by mkorolyov** [comment]
@dhui Hey, could you please take a look?

**Comment by guy9** [comment]
@dhui any chance you can have a look?

**Review by dhui — APPROVED** [review]
@mkorolyov Thanks for the PR and sorry for the slow response. I'll merge this and make some changes

**Pull request merged**
